language: node_js
node_js:
  - '10'
script: npm run build
before_install:
  - openssl aes-256-cbc -K $encrypted_ec548dad3e55_key -iv $encrypted_ec548dad3e55_iv -in .travis/id_rsa_deploy.enc -out .travis/id_rsa_deploy -d
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script: bash scripts/deploy.sh